### ISSUE TITLE
Sobre el espacio en Madrid y en la Casa encendida

### ISSUE THREAD

**Issue by VGCif** [WoBitcoin/WoBitcoin#9]
Otra ciudad: 
- Madrid es tan caro que tengo la impresión que el espacio se comió todo el presupuesto, España tiene muchas grandes ciudades bien conectadas con precios muy accesibles tanto en espacios como para los alojamientos de los asistentes
- En cualquier otra gran ciudad española se consiguen espacios mucho mejores por menor coste

**Comment by VGCif** [comment]
El espacio de la Casa Encendida:
- No promocionó nada el evento, ni un solo cartel en el propio espacio
- Tener las charlas en el sótano y el espacio de Networking en la 4° planta, hacia muy incómodo ir a ambos espacios

**Comment by Heptapodae** [comment]
Bueno, yo creo que dentro del mismo Madrid se pueden encontrar barrios o regiones más baratas. Se perdería lo "céntrico" de la localización de esta pasada edición pero creo que se puede tener un buen equilibrio. 
Sobre la promoción de La Casa Encendida, creo que comentaron que, al ser un evento privado, ellos no lo publicitan. Pero eso que lo diga mejor WatchOutFreedom, que me parece que ellos conocían gente ahí.

**Comment by decentralizedb** [comment]
Hemos buscado hacerlo fuera, pero las opciones por loco que parezca no han sido muchas
Repetimos Madrid porque ha sido la mejor oferta aunque sigue siendo cara por el espacio, por el tema logístico con gente que traemos de fuera no lo es.
Creo que este año les va a gustar el sitio, ya lo verán pronto.
Gracias mil por los comentarios y perdón por no contestar antes, entre que no teníamos cerrado sitio y que el día a día nos come, no había podido!
